# --- ETAPA 1: COMPILAÇÃO ---
FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o sensor_manual_bin aplicacoes/sensor_manual/sensor_manual.go

# --- ETAPA 2: EXECUÇÃO ---
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/sensor_manual_bin .

# -it obrigatório para funcionar o terminal interativo
ENTRYPOINT ["./sensor_manual_bin"]