# --- ETAPA 1: COMPILAÇÃO ---
FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o teste_bin aplicacoes/teste/teste.go

# --- ETAPA 2: EXECUÇÃO ---
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/teste_bin .

ENTRYPOINT ["./teste_bin"]